[package]
name = "ecosystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
big-brain = "0.15.0"
bevy_turborand = "0.4.0"
bevy_mod_picking = "0.10"
