[package]
name = "ecosystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
big-brain = { git = "https://github.com/Weibye/big-brain.git", branch = "bevy-0.9" }
bevy_turborand = "0.4.0"